# Conversation states
(
    WELCOME,
    TERMS_AGREEMENT,
    NAME,
    GENDER,
    AGE,
    TIMEZONE_SELECTION,
    NOTIFICATION_FREQUENCY,
    TIME_FORMAT,
    MAIN_MENU,
    BOT_CAPABILITIES,
    THERAPIST_QUESTION,
) = range(11)

# Emotion diary states - CHANGED TO STRINGS
EMOTION_SELECTION = "EMOTION_SELECTION_STATE"
GOOD_STATE_SELECTION = "GOOD_STATE_SELECTION_STATE"
BAD_STATE_SELECTION = "BAD_STATE_SELECTION_STATE"
GOOD_STATE_QUESTION = "GOOD_STATE_QUESTION_STATE"
BAD_STATE_QUESTION = "BAD_STATE_QUESTION_STATE"
GOOD_STATE_OPTIONS = "GOOD_STATE_OPTIONS_STATE"
BAD_STATE_OPTIONS = "BAD_STATE_OPTIONS_STATE"
GOOD_STATE_FINAL = "GOOD_STATE_FINAL_STATE"
BAD_STATE_FINAL = "BAD_STATE_FINAL_STATE"
GOOD_OPTION_SELECTION = "GOOD_OPTION_SELECTION_STATE"
BAD_OPTION_SELECTION = "BAD_OPTION_SELECTION_STATE"
AFTER_SUPPORT_MESSAGE = "AFTER_SUPPORT_MESSAGE_STATE"

# Thought Diary States
THOUGHT_DIARY_START = "THOUGHT_DIARY_START_STATE" # Initial state when entering thought diary
THOUGHT_DIARY_AWAITING_POSITIVE_ENTRY = "THOUGHT_DIARY_AWAITING_POSITIVE_ENTRY_STATE"
THOUGHT_DIARY_AWAITING_NEGATIVE_ENTRY = "THOUGHT_DIARY_AWAITING_NEGATIVE_ENTRY_STATE"
THOUGHT_DIARY_NEGATIVE_QUESTIONING = "THOUGHT_DIARY_NEGATIVE_QUESTIONING_STATE" # New state for follow-up questions
THOUGHT_DIARY_AWAITING_POSITIVE_FEEDBACK = "THOUGHT_DIARY_AWAITING_POSITIVE_FEEDBACK_STATE" # After positive entry, for 'back to main' button
THOUGHT_DIARY_AWAITING_NEGATIVE_ACTION = "THOUGHT_DIARY_AWAITING_NEGATIVE_ACTION_STATE" # After negative entry, shows "get recommendation" buttons
THOUGHT_DIARY_AWAITING_RECOMMENDATION_FEEDBACK = "THOUGHT_DIARY_AWAITING_RECOMMENDATION_FEEDBACK_STATE"
THOUGHT_DIARY_AWAITING_RECONSIDER_FEEDBACK = "THOUGHT_DIARY_AWAITING_RECONSIDER_FEEDBACK_STATE"

# Reflection states
REFLECTION_VALUABLE_LEARNED = "REFLECTION_VALUABLE_LEARNED_STATE"
REFLECTION_OPENNESS_LEVEL = "REFLECTION_OPENNESS_LEVEL_STATE"
REFLECTION_OBSTACLES = "REFLECTION_OBSTACLES_STATE"
REFLECTION_NEXT_TOPICS = "REFLECTION_NEXT_TOPICS_STATE"
REFLECTION_CONFIRMATION = "REFLECTION_CONFIRMATION_STATE"

# Session scheduling states
SESSION_DATE_TIME_INPUT = "SESSION_DATE_TIME_INPUT_STATE"
SESSION_CONFIRMATION = "SESSION_CONFIRMATION_STATE"

# Notification settings states
NOTIFICATION_FREQUENCY_SELECTION = "NOTIFICATION_FREQUENCY_SELECTION_STATE"

# Timezone selection state
TIMEZONE_SELECTION_STATE = "TIMEZONE_SELECTION_STATE"

# Emotion analysis states
EMOTION_ANALYSIS_PERIOD_SELECTION = "EMOTION_ANALYSIS_PERIOD_SELECTION_STATE"

# Weekly reflection states
WEEKLY_REFLECTION_START = "WEEKLY_REFLECTION_START_STATE"
WEEKLY_REFLECTION_SMILE_MOMENT = "WEEKLY_REFLECTION_SMILE_MOMENT_STATE"
WEEKLY_REFLECTION_KINDNESS = "WEEKLY_REFLECTION_KINDNESS_STATE"
WEEKLY_REFLECTION_PEACE = "WEEKLY_REFLECTION_PEACE_STATE"
WEEKLY_REFLECTION_NEW_DISCOVERY = "WEEKLY_REFLECTION_NEW_DISCOVERY_STATE"
WEEKLY_REFLECTION_GRATITUDE = "WEEKLY_REFLECTION_GRATITUDE_STATE"

# Therapy themes states
THERAPY_THEMES_MENU = "THERAPY_THEMES_MENU_STATE"
THERAPY_THEMES_PERIOD_SELECTION = "THERAPY_THEMES_PERIOD_SELECTION_STATE"
THERAPY_THEMES_VIEWING = "THERAPY_THEMES_VIEWING_STATE"
THERAPY_THEMES_DELETE_INPUT = "THERAPY_THEMES_DELETE_INPUT_STATE"
THERAPY_THEMES_DELETE_CONFIRMATION = "THERAPY_THEMES_DELETE_CONFIRMATION_STATE"
THERAPY_THEMES_ADD_INPUT = "THERAPY_THEMES_ADD_INPUT_STATE"
THERAPY_THEMES_ADD_EDIT = "THERAPY_THEMES_ADD_EDIT_STATE"

# Relaxation methods states
RELAXATION_FORMAT_SELECTION = "RELAXATION_FORMAT_SELECTION_STATE"
RELAXATION_AUDIO_LIST = "RELAXATION_AUDIO_LIST_STATE"
RELAXATION_VIDEO_LIST = "RELAXATION_VIDEO_LIST_STATE"

# Voice message confirmation states
VOICE_TRANSCRIPTION_CONFIRMATION = "VOICE_TRANSCRIPTION_CONFIRMATION_STATE"

# Therapist question state  
THERAPIST_QUESTION_STATE = "THERAPIST_QUESTION_STATE"

# Referral source states
REFERRAL_SOURCE_STATE = "REFERRAL_SOURCE_STATE"
REFERRAL_SOURCE_INPUT_STATE = "REFERRAL_SOURCE_INPUT_STATE"